name: titipin2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/Garage1.png
     - images/Garage11.png
     - images/Garage2.png
     - images/Garage3.png
     - images/Sukses.png
     - images/Reguler.png
     - images/VIP.png
     - images/Garage4.png
     - images/mobil1.png
     - images/btnhometap.png
     - images/btnhome.png
     - images/btntambahmobil.png
     - images/btntambahmobiltap.png
     - images/btnreservasi.png
     - images/btnreservasitap.png
     - images/btnlacak.png
     - images/btnlacaktap.png
     - images/btndetaillacakmobil.png
     - images/btnprofil.png
     - images/btnprofiltap.png
     - images/Garage12.png
     - images/datamobil.png
     - images/iconeditmobil.png
     - images/icondetailmobil.png
     - images/iconpoin.png
     - images/iconpassword.png
     - images/iconcustomerservice.png
     - images/iconlogout.png
     - images/iconpanahlokasi.jpg
     - images/profilepicture.png
     - images/mapsreservasi1.png
     - images/mapsreservasi2.png
     - images/btndropdown.jpg
     - images/btndropdown2.jpg
     - images/btndropdownred.jpg
     - images/btndates.jpg
     - images/icondates.jpg
     - images/btnback.png
     - images/iconsedangdicuci.png
     - images/icondalamperjalanan.png
     - images/icondigarasi.png
     - images/mapsdetailmobil.png
     - images/mapscheckout.png
     - images/gps.jpg
     - images/iconpanahkanan.png
     - images/iconpanahkiri.png
     - images/iconpanahbawah.png
     - images/iconwhatsapp.png
     - images/icontelegram.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

              
  fonts:
    - family: PT Sans Narrow
      fonts:
        - asset: fonts/PTSansNarrow-Bold.ttf
        - weight: 700

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
        - weight: 700

    - family: Titillium Web
      fonts:
        - asset: fonts/TitilliumWeb-Bold.ttf
        - weight: 700
        - asset: fonts/TitilliumWeb-SemiBold.ttf
        - weight: 600
        - asset: fonts/TitilliumWeb-Regular.ttf
        - weight: 400
    
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - weight: 700
          
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
